export const NASA_DATA_FETCH = "NASA_DATA_FETCH";
export const NASA_DATA_IS_LOADING = "NASA_DATA_IS_LOADING";
export const NASA_MORE_DATA_LOADING = "NASA_MORE_DATA_LOADING";
export const NASA_FETCH_ERROE = "NASA_FETCH_ERROE";
